language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
  - pypy
env:
  - DJANGO="Django<1.9"       # Django 1.8.x (LTS version)  |   2.7, 3.2 (until the end of 2016), 3.3, 3.4, 3.5
  - DJANGO="Django<1.10"      # Django 1.9.x                |   2.7, 3.4, 3.5
  - DJANGO="Django<1.11"      # Django 1.10.x               |   2.7, 3.4, 3.5
  - DJANGO="Django==1.11rc1"  # Django 1.11.x               |   2.7, 3.4, 3.5, 3.6
before_install:
  - export DJANGO_SETTINGS_MODULE=django_custom_500.example_project.settings
install:
    - pip install --quiet --upgrade "$DJANGO"
    - pip install django-annoying
    - pip install requests
    - pip install nose
    - pip install coveralls
    - pip install future
    - pip install six
script:
    - rm -f fabfile.py
    - python setup.py build
    - python setup.py sdist
    - python setup.py bdist_wheel
    - nosetests -v --with-coverage --cover-package=django_custom_500 --cover-tests --cover-erase --with-doctest --nocapture
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.9.5
