language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
# - nightly
env:
  - DJANGO=1.4.0
  - DJANGO=1.4.20
  - DJANGO=1.5.0
  - DJANGO=1.5.12
  - DJANGO=1.6.0
  - DJANGO=1.6.11
  - DJANGO=1.7.0
  - DJANGO=1.7.11
  - DJANGO=1.8.7
  - DJANGO=1.9.0
install:
    - pip install -q Django==$DJANGO
    - pip install django-annoying
    - pip install requests
    - pip install nose
    - pip install coveralls
    - pip install future
    - pip install six
script:
    - rm -f fabfile.py
    - python setup.py build
    - python setup.py sdist
    - python setup.py bdist_wheel
    - nosetests -v --with-coverage --cover-package=django_custom_500 --cover-tests --cover-erase --with-doctest --nocapture
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    # Taken from: https://github.com/darklow/django-suit/blob/develop/.travis.yml
    # Django doesn't support following combinations
    - python: 3.3
      env: DJANGO=1.4.0
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.4
      env: DJANGO=1.4.0
    - python: 3.4
      env: DJANGO=1.4.20
    - python: 2.6
      env: DJANGO=1.6.0
    - python: 2.6
      env: DJANGO=1.6.11
    - python: 2.6
      env: DJANGO=1.7.0
    - python: 2.6
      env: DJANGO=1.7.11
    - python: 2.6
      env: DJANGO=1.8.0
    # Fails. Django issue #19944
    # https://code.djangoproject.com/ticket/19944
    - python: pypy
      env: DJANGO=1.5
    - python: pypy
      env: DJANGO=1.5.12
