language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=1.8.12
  - DJANGO=1.9.5
before_install:
  - export DJANGO_SETTINGS_MODULE=django_custom_500.example_project.settings
install:
    - pip install -q Django==$DJANGO
    - pip install django-annoying
    - pip install requests
    - pip install nose
    - pip install coveralls
    - pip install future
    - pip install six
script:
    - rm -f fabfile.py
    - python setup.py build
    - python setup.py sdist
    - python setup.py bdist_wheel
    - nosetests -v --with-coverage --cover-package=django_custom_500 --cover-tests --cover-erase --with-doctest --nocapture
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.9.5
